Add fetch options for custom headers
conveyal/isomorphic-mapzen-search pull request #47
Opened 2020-01-31 22:06 UTC by landonreed

fix #46. This simply allows for passing fetch options from any request type (e.g., autocomplete) to where fetch is called.

2020-02-01 04:55 UTC, evansiroky requested changes
Great code and test cases. The API documentation needs to be updated though. You can run this command:

```shell
$ yarn generate-docs
```

2020-02-03 23:21 UTC, landonreed commented
Thanks, @evansiroky, just pushed a commit with the docs changes.

2020-02-04 00:16 UTC, evansiroky approved these changes

2020-02-12 16:13 UTC, merged

2020-02-12 16:46 UTC, landonreed commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/isomorphic-mapzen-search)
- [GitHub release](https://github.com/conveyal/isomorphic-mapzen-search/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: